apiVersion: v1
kind: Service
metadata:
  name: mxcro-frontend-service
spec:
  selector:
    app: mxcro
    microservice: frontend
  ports:
    - port: {{ .Values.portNumber }}
      targetPort: {{ .Values.portNumber }}
  type: {{ .Values.serviceType }}

