name: Default CI/CD pipeline
run-name: ${{ github.actor }} started workflow ${{ github.workflow }}, with run ID ${{ github.run_id }}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:

  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: k8s/Containerfile
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/mxcro-frontend:build-${{ github.run_id }}
            ${{ vars.DOCKER_USERNAME }}/mxcro-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: publish-image
    steps:
     - uses: actions/checkout@v4
     - uses: azure/setup-kubectl@v4
       with:
          version: "latest"
     - uses: azure/setup-helm@v4.2.0
       with:
          version: "latest"
     - run: echo "${{ secrets.KUBECONFIG }}" > ${{ github.workspace }}/kubeconfig
     - env:
         KUBECONFIG: ${{ github.workspace }}/kubeconfig
       run: helm upgrade --install mxcro-frontend k8s/helm-mxcro-frontend

